### ISSUE TITLE
format other locale does not work!

### ISSUE THREAD

**Issue by hamedsbt** [smmoosavi/date-fns-jalali#20]
```
import enUS from 'date-fns-jalali/esm/locale/en-US';
import {format, parseISO} from 'date-fns-jalali/esm';
```
```
format(new Date, 'yyyy-MM-dd', {locale: enUS})
format(parseISO('1399-12-20'), 'yyyy-MM-dd', {locale: enUS})
```
I'v expect it return today as enUS date but it return jalali date.

**Comment by smmoosavi** [comment]
Thanks for the issue, Other unused locales are removed. Right now, only the `fa-IR` and `en-US` locale remained (v2.19.0-2).

```ts
import enUS from 'date-fns-jalali/locale/en-US';
import { format } from 'date-fns-jalali';

console.log(format(parseISO('2021-03-17'), 'yyyy-MMMM-dd')); // 1399-اسفند-27
console.log(format(parseISO('2021-03-17'), 'yyyy-MMMM-dd', { locale: enUS })); // 1399-Esfand-27

```
**Note1:** ParseJSON, ISO-related, and RFC-related functions work with gregorian calendar logic.
**Note2:** If you need gregorian calendar logic for the `format` and `parse` functions, you should use `date-fns`.
